### ISSUE TITLE
Is mubot Dead after GDPR

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [davidar/hubot-matrix#15]
Title says all.  Not much activity here, and after GDPR we have not seen mubot and perhaps there should be a fork.  Also discussed in [Fork mubot or Mimic Some of it's Functions #125](https://github.com/turt2live/matrix-wishlist/issues/125).

**Comment by davidar** [comment]
Not deliberately, but I don't really use mubot much myself anymore, so it tends to crash without me noticing. Of course anyone is free to run their own hubot instance using this adapter
