### ISSUE TITLE
Putting out a CFM (Call For co-Maintainers)?

### ISSUE THREAD

**Issue by patcon** [davidar/hubot-matrix#18]
Hi, David!

First off, thanks a ton for creating this adapter and sharing it. Totally appreciate the energy that went into offering this :)

But on to the main question: Might you be willing to let me run a call for co-maintainers to help you merge existing PRs and maintain this project going forward?

It seems like maybe you've been busy lately (which is a-ok!), and so forks are proliferating and people are starting other disconnected projects. I'd love to help rally people around a single project, and yours would be a good place to start if you were willing to entertain the premise of others having push access :)

If you were willing, then all I would do would be to go through the commit and issue history, and nominate some folks who've made contributions in the past. I'd also check out their other github activity, and try to factor in how active they are on the platform, and how experienced they seem to be. (I wouldn't assume I'd get merge access myself, as I recognize I'm new here.)

It would be your call in the end to add these new maintainers as empowered contributors to the repo. I'd also be dependant on you to give that your full consideration, in order to move things forward, if that sounds fair :)

What are your thoughts on this? Are you open to letting me move forward with the idea, or willing to workshop it and suit it to your preferences?

Alternatively, we could try to re-energize another repo, but I'd really rather try it here!

Anyhow, thanks a lot for your attention on this issue 🎉

**Comment by davidar** [comment]
Sure, thanks for offering to help :)

Would it help if I added this repo to https://www.codeshelter.co/? (I haven't used it much, so I don't know whether or not it's helpful for this kind of thing)

**Comment by patcon** [comment]
Woo! Thanks! Not a bad idea, but I think I can more easily run with some things here first :) anyone who's been here before has already checked the hardest boxes.

**Comment by xurizaemon** [comment]
Hey there @patcon @davidar - I'm looking at this project for Hubot v3 currently, and happy to assist also.

**Comment by xurizaemon** [comment]
Hi @davidar - are you open to extending merge rights to other contributors? I'm still happy to assist if so. Have no current changes I plan to make, just nudging this issue while there's capacity to do it.

Github has good collaborative tools for this, I suspect we don't need to add Codeshelter to the mix as you already have a couple of volunteers stepping forward in this issue.

**Comment by davidar** [comment]
Sure, I'm still open to that. I'm not sure about granting the rights pre-emptively, but if there's any maintenance you want to do I'm happy to give you the access you need.

**Comment by patcon** [comment]
Ah neat, hadn't heard of codeshelter! I like their approach of no-harm-no-foul, kinda-just-as-backup approach to adding vetted maintainers in the slow moments, to support when official maintainer is busy. Didn't realize that was their value-prop until now :) https://www.codeshelter.co/projects/add/

**Comment by davidar** [comment]
Thanks for the PRs @xurizaemon, I've added you as a collaborator so you can merge changes yourself in the future.

**Comment by xurizaemon** [comment]
Thanks @davidar, appreciated!
