### ISSUE TITLE
Auto-accept invitations

### ISSUE THREAD

**Issue by xurizaemon** [davidar/hubot-matrix#21]
Currently there's a manual step for our setup where each bot needs a human to log in and accept invites to each channel the bot is brought into. If the adapter could be configured to auto-accept each invite, that would save a lot of work.

I believe this is the default behaviour in Hubot for IRC, RocketChat and Mattermost - not sure about other adapters.

Hmm ... is this already the expected behaviour? Looks like it, but I'm not seeing that so I need to dig into that.

https://github.com/davidar/hubot-matrix/blob/7ea8a6bf0bf73c61520d99abe15211c2cabeae1f/src/matrix.js#L175-L181

**Comment by davidar** [comment]
Yeah, at least it used to auto-accept them, I guess something on the matrix side has changed since then

**Comment by xurizaemon** [comment]
I believe this was a function of our server's configuration - so far we've been able to resolve this by enabling federation per-room, after the server was initially configured to not support federation. I don't understand the server internal details, but I think we should close this until someone else reports same and re-opens.

(I'll try to add screenshots of working and non-working room details when I'm back on a work laptop.)
